version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

executors:
  node:
    docker:
      - image: cimg/node:18.20.4
    working_directory: &working_directory ~/each-arg

commands:
  npm_publish:
    steps:
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish to npm
          command: npm publish

jobs:
  test_and_build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-deps-each-arg-{{ checksum "package.json" }}
            - v4-deps-each-arg-
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v4-deps-each-arg-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: npm test
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: *working_directory
          paths:
            - .

  upload_coverage:
    executor: node
    steps:
      - attach_workspace: &attach_workspace
          at: *working_directory
      - codecov/upload:
          file: coverage/*.json

  publish_to_npm:
    executor: node
    steps:
      - attach_workspace: *attach_workspace
      - npm_publish

workflows:
  workflow:
    jobs:
      - test_and_build:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - upload_coverage:
          requires:
            - test_and_build
          filters:
            branches:
              only: /main/

      - publish_to_npm:
          context: npm
          requires:
            - test_and_build
          filters:
            tags:
              only: /^v\d+\.\d+\.\d+$/
            branches:
              ignore: /.*/
